modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="berserkmod"
version="0.0.1"
displayName="Berserk Mod"
description='''
A mod inspired by Berserk anime/manga
'''
authors="akul"

[[dependencies.berserkmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.berserkmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"